add_subdirectory(src/protocol)
add_subdirectory(src/core)
add_subdirectory(src/transport)
add_subdirectory(extensions/media_provider)
add_subdirectory(benchmarks)

if(BUILD_TESTS)
  add_subdirectory(tests)
endif()

set(FLOWMQ_PROTOCOL_SOURCES ${FLOWMQ_PROTOCOL_SOURCES} PARENT_SCOPE)
set(FLOWMQ_PROTOCOL_HEADERS ${FLOWMQ_PROTOCOL_HEADERS} PARENT_SCOPE)
set(FLOWMQ_CORE_SOURCES ${FLOWMQ_CORE_SOURCES} PARENT_SCOPE)
set(FLOWMQ_CORE_HEADERS ${FLOWMQ_CORE_HEADERS} PARENT_SCOPE)
set(FLOWMQ_TRANSPORT_SOURCES ${FLOWMQ_TRANSPORT_SOURCES} PARENT_SCOPE)
set(FLOWMQ_TRANSPORT_HEADERS ${FLOWMQ_TRANSPORT_HEADERS} PARENT_SCOPE)
set(FLOWMQ_MEDIA_PROVIDER_SCHEMA ${FLOWMQ_MEDIA_PROVIDER_SCHEMA} PARENT_SCOPE)
set(FLOWMQ_MEDIA_PROVIDER_SOURCE ${FLOWMQ_MEDIA_PROVIDER_SOURCE} PARENT_SCOPE)
set(FLOWMQ_MEDIA_PROVIDER_GENERATED_DIR
    ${FLOWMQ_MEDIA_PROVIDER_GENERATED_DIR}
    PARENT_SCOPE)
set(FLOWMQ_MEDIA_PROVIDER_GENERATED_HEADER
    ${FLOWMQ_MEDIA_PROVIDER_GENERATED_HEADER}
    PARENT_SCOPE)
set(FLOWMQ_MEDIA_PROVIDER_GENERATED_SOURCE
    ${FLOWMQ_MEDIA_PROVIDER_GENERATED_SOURCE}
    PARENT_SCOPE)
set(FLOWMQ_MEDIA_PROVIDER_CODEGEN_TARGET
    ${FLOWMQ_MEDIA_PROVIDER_CODEGEN_TARGET}
    PARENT_SCOPE)
